option26/quarantine-hero

src/components/FilteredList.js

* fixes #16 --> currently, the info text is not shown if the search returned no results
* updated info text (removed redundant word)
@florianschmidt1994

show correct info text if no filtered entries were found

---

src/views/Dashboard.jsx

This was due to not waiting for authentication from firebase before
redirecting to the signup page. Now, the value `undefined` is used when
no authentication information is available and the special string
'NOT_LOGGED_IN' is used to denote the state where it has been determined
that the user is not logged in.
I have tested that
* still redirects to the signup page when not logged in and
* the dashboard page still shows notifications.
I have not tested that the dashboard page still shows requests for help and their responses because I didn't want to create a fake request for help just for testing purposes.

Fix temporary redirect on dashboard page after reload when logged in

---

package.json
src/components/FilteredList.jsx

* fixes #89 
documentation for helper function: https://lodash.com/docs/4.17.15#orderBy

Bug fix: add local sorting if location filter is active

---

.github/pull_request_template.md
src/index.jsx
src/serviceWorker.jsx
src/views/AskForHelp.jsx
src/views/CompleteOfferHelp.jsx

This silences the remaining eslint errors. The primary motivation is to have a clean slate for future contributions and not always spam all pull requests with the eslint output of preexisting errors.
Closes #115
**Checklist**

Disable remaining eslint warnings

---

src/App.jsx
src/components/ArrowDown.jsx
src/util/createEventListener.jsx

These hooks should return a function that removes the event listener.
Otherwise, there could be a reference to a component that has already
been removed, which causes an error to be logged in the console during
development.
There should be no user-visible changes (except perhaps slightly better performance / lower memory usage).
**Checklist**
- @kenodressel
- @Maurice22
- @tgraupne

Fix usages of addEventListener in useEffect hook

---

README.md
src/components/Entry.jsx

Again just a small thing...
The last code block of the `README` wasn't closed correctly which led to wrong formatting.
Also added a language qualifier to the console snippet.
**Checklist**
@florianschmidt1994

Fix README codeblock

---

public/index.html

Setting the language for Gmaps API Calls to german to prevent locations being displayed in different languages in the entries.
Fixes #160 
**Checklist**

Fix language for Google Maps API calls to german

---

src/i18n.js

The motivation for this change is that we do
not need the debug output logging from i18next
and it clutters the console
Close #176
**Checklist**

Disable i18next debug logging

---

src/components/OnePagers.jsx
src/views/Main.jsx
src/views/Overview.jsx

- Use the OnePagers component on /#/overview
- Refactor OnePagers to not have a margin
- Use wrapper div in Main.jsx for adding margin
Close #169
**Checklist**

Use correct OnePagers component on overview

---

.gitignore

It adds cypress video output `/cypress/video/*` and screenshots `/cypress/screenshots/*`
to `.gitignore`. I believe we should not have those in version control and it follows common practice as described in https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Folder-Structure
**Checklist**

Ignore cypress screenshots and videos in git

---

src/components/Entry.jsx

* the updated firebase function for `/delete` requires the `collectionName` parameter, to know from which collection the responses subcollection should be migrated from
* [corresponding code in firebase functions](https://github.com/florianschmidt1994/quarantaenehelden-firebase-functions/blob/master/functions/index.js#L305)
* Currently, the  `collectionName`  is not set on delete, resulting in an error when trying to migrate the responses to the `deleted` collection
**Checklist**

fix delete for ask-for-help documents with updated firebase functions

---

src/services/GeoService.js

Before applying this fix, the status 'ZERO_RESULTS' would mean
that we return a rejected Promise, which will be caught in LocationInput
and reported as an error to Sentry.
With this fix we resolve the Promise with an empty array and default to
rejecting the Promise for all other statuses.
I've tested that the input still works as expected manually
Close #189
**Checklist**

Fix zero geocoding results to resolve to empty array

---

firebase/functions/index.js

Fix linting errors by adding spaces before and after `{` `}`

Fix linting errors in firebase index.js

---

src/views/AskForHelp.jsx
src/views/VerifyEmail.jsx

* fixes #197 (this is currently only happening on staging, since the firebase functions on prod have been updated yet)
* currently, a user with an unverified email can attempt to create a new listing, even though he should verify his email first
* the listing creation itself fails due to the security rules, which is fine
* additionally, the listing creation fails in the first session for a user even though if the user is verified
* the reason for this is the fact that the firebase backend is not aware yet that the user email is verified, for this we need to force refresh the ID token https://stackoverflow.com/questions/47243702/firebase-token-email-verified-going-weird
_Briefly describe your changes here_
* adds a redirect on the `ask-for-help` view …

add redirect to verify-email if email is not verified

---

src/views/Main.jsx

Scrolling down to thee right position on small screens now by adding a conditional offset based on the media query. The underlying issue is that we show the menu bar on mobile but not on desktop, so on mobile it overlaps the buttons.
**Checklist**

Scroll to the right position when menu bar visible

---

.github/workflows/deploy-frontend.sh

It now allows "empty" commits to gh-pages. This should remove the CI error when the deployed code is not updated. Is a fix to #194

fixes frontend deploy script

---

src/components/EntryMap.jsx

Some entries have lat/lon zero which leads to an error
when we try to extract the data with the firebase library.
Instead of crashing when one entry has this problem, we
are now filtering out those invalid entries and logging
an error instead.
Note that in production we should not have those entries
and they indicate that something is wrong in another place,
which is why I've added reporting to sentry if any of those
invalid entries should occur.
Close #220

Catch errors when parsing entries

---

.github/workflows/deploy.yaml
README.md

This uses https://github.com/tclindner/sentry-releases-action to create
a new release on sentry whenever we deploy to production.
@kenodressel and @maurice22 please make sure to create such a secret
and add it to the project before merging this.
Close #222

Use workflow to create a new sentry release on deploy

---

src/util/parseDoc.js

Depending on which way we use to retrieve data (i.e. firestore or geofirestore) we need to access a different key. Was broken in last master in last deploy.

Fixed data retrieval for geofirestore

---

src/styles/App.css
src/views/Main.jsx

From the `Main` component, removes a logo which is only shown on mobile so that only the logo from the `MobileTopNavigation` component is visible. Closes #235.

Remove QH logo duplication on mobile main page

---

src/views/Signup.jsx

When defining the signin function, instead of using the passed mail parameter, it is using the global email parameter (from the react state). This was fixed now.

Fixed usage of wrong parameter

---

src/components/EntryMap.jsx

I updated the asset reference in the img tag of the logo.
It now uses the new gender-fluid super hero who need help.

Bug fix: updated the logo inside the map

---

firebase/functions/index.js
src/components/entry/Entry.jsx
src/views/OfferHelp.jsx

As suggested in #218, adding a link to report an entry would be nice. This PR introduces a query param "reported" to the /offer-help/{id} view. When set, the entry on this page will be displayed in the attemptReport state so that a user can report the post there. Furthermore, it passes this url to the sendgrid template.
Before this can be merged, we need to adapt the sendgrid template.

Query param to display entry in attempt report state

---

src/components/entry/Entry.jsx

This PR introduces three new analytics events for the engagement with `ask-for-help` entries, namely:
* `help_request_deleted`
* `help_request_solved`
* `help_request_reported`
Adding these events allow us to run better analytics in the future. I tried to align the naming with the existing events, e.g. [success_request_help](https://github.com/kenodressel/quarantine-hero/blob/21075a4e8c50898dab9e3bf39617b767579914a3/src/views/Success.jsx#L8)

add analytics events for engagement with entry

---

public/locales/de/translation.json
src/components/Responses.jsx
src/components/entry/Entry.jsx

Changes the timestamps for entries and responses so that they have correct grammar. Closes #265.
earlier: "vor etwa eine Stunde" -> now: "vor etwa einer Stunde"
earlier: "vor ein Tag" -> now: "vor einem Tag"
earlier: "vor 2 Tage" -> now: "vor 2 Tagen"

Fix grammatical case of German timestamps for entries and responses

---

src/components/EntryList.jsx

When a user is clicking on an address inside an entry, we update the search. However, when the user clicks on the browser "Back" button, we don't clear the search again. This PR introduces the functionality to navigate back after clicking on an address to clear the search.

Navigate to clear search

---

firebase/functions/hotline.js
firebase/functions/index.js
firebase/functions/package-lock.json
firebase/functions/package.json

This adds a firebase function `handleIncomingCall` which allows use to expose phone numbers from a call sheet in google drive via http.
```
Twilio <--> Firebase Function <--> Google Sheets API
```
A request to `handleIncomingCall` will return a list of phone numbers that are available to pick up calls right now as comma-separated values. All requests to this endpoint are protected by a token.
**Checklist before deploying this function**
Set the following config values accordingly
Use the command 
```sh
firebase functions:config:set googleSheets.<key>=<VALUE> --project quarantine-hero
```
**Checklist after deploying this function**
- Set the URL of the `handleIncomingCall` in Twilio studio
There unfortunately is no issue to track …

Add function to serve hotline numbers from google sheet

---

firebase/functions/index.js

When a person asks for help (helpee) receives an offer from someone (helper) to help, we send an email to the helpee. Within this email we want to add a link back to the place where entry which was created by the helpee when asking for help. 
This PR adds the id of this entry in order to modify the email template to do this.
Closes #261

Add askForHelpId to sendgrid dynamic template variables for offer-help

---

src/App.jsx
src/util/emailVerified.js
src/views/AskForHelp.jsx
src/views/Signin.jsx
src/views/Signup.jsx
src/views/VerifyEmail.jsx

**The problem**
The user object exposed by firebase has a property called `emailVerified`. This property updates based on the information which is saved in the user database of firebase. It gets updated whenever we load the user information, i.e. via `useAuthState(firebase.auth())`. 
This means that when a user verifies himself and we redirect to another page or a browser refresh happens, that this property is `true`.
Firebase internally uses a JWT for authenticating against its different APIs. This token contains a claim `emailVerified`. This claim is only updated when a user performs a `signIn` or when `user.refreshIdToken(true /* force refresh */)` is called in the code.
It can now happen that a user verifies his email in a different browser than the one he is using to interact with …

Fix issue where token and user object are out of sync

---

src/views/HandleEmailAction.jsx

When a user opens a verify email link in a browser it is currently logged in, the user gets logged out first. The issue was, that a user could be logged in with a different user than the one it tries to verify the email for. This would cause confusion after email verification.

Logging out user on verify email

---

firebase/functions/index.js
firebase/functions/utils.js
public/locales/de/translation.json
src/App.jsx
src/components/Responses.jsx
src/views/CompleteNotification.jsx
src/views/Dashboard.jsx
src/views/NotifyMe.jsx

* Adds a button to the Dashboard that allows users to delete their account
* Upon clicking, the user has to reenter the PW to confirm the account deletion
* Once the account is deleted in Firebase, a cloud function is triggered, deleting all data associated with the user
* For reported posts, we replace any user did by "ghost-user" in order to not loose this information completely
**TODOs before merge**
This feature requires us to rename the collection /offer-help. I renamed it to /notifiactions as this is what is stored in the collection.
Closes #62

Delete account feature

---

firebase/functions/package-lock.json
firebase/functions/package.json

* Removes `@types/moment-timezone`, as they are now shipped with `moment-timezone`.
* https://github.com/moment/moment-timezone/issues/858

upgrade moment-timezone, remove @types/moment-timezone

---

src/components/Responses.jsx
src/components/entry/Entry.jsx
src/util/getDateFnsLocaleObject.js

Use the language selected through i18next for date-fns to localize time distances. Closes #276 
To see what this does exactly although currently German is force-selected as the language by i18next, you can comment out the `lng` option in `i18n.js` and set a cookie `i18next` to the desired language e.g. `en-US`, `ru`, ...

Use i18next language to select date-fns locale

---

src/components/Routes.jsx
src/firebase.js
src/util/CookieConsent.jsx

Analytics are currently not working, because we missed adding functionality to enable them when we refactored the cookie consent. This is fixed now fixed by initializing them once the cookie consent is given (with `setAnalytics`)

Fix analytics cookie consent

---

public/index.html

* updates `meta title` tag to include `Nachbarschaftshilfe` (as `wir gegen corona` does)
* updates content of `noscript` tag to improve accessibility
To quote from [googles support article](https://support.google.com/webmasters/answer/66353?hl=en#:~:text=Hiding%20text%20or%20links%20in,text%20on%20a%20white%20background):
In general, hidden tex is perceived deceptive, but:
> However, not all hidden text is considered deceptive. For example, if your site includes technologies that search engines have difficulty accessing, like JavaScript, images, or Flash files, using descriptive text for these items can improve the accessibility of your site
> JavaScript: Place the same content from the JavaScript in a <noscript> tag. If you use this method, ensure …

SEO improvements v2: update title and noscript content

---

src/util/useQuery.js

Our currently most triggered error occurs in HandelEmailActions.jsx, whenever the mode of the firebase action is undefined. This currently happens a lot as the custom `useQuery()` hook returns an empty object at first, which makes `mode` undefined and hence leads to the error.
This fix is a rewrite of the `useQuery()` hook so that it does not return an empty object initially. The code is inspired by this https://github.com/ReactTraining/react-router/blob/085d0a862c33f9cfbbf825fddb643cbc0ed44243/packages/react-router-dom/examples/QueryParams.js#L29 and the code we already had in place

Fixing undefined email action error

---

public/locales/de/translation.json
src/views/AskForHelp.jsx
src/views/HandleEmailAction.jsx
src/views/Signin.jsx

This PR arose from #375. However, it seems to be unfeasible what is described there. As a result, I only improved the wording for the PW reset button to signal, that users who haven't set their password yet (i.e. just enabled notification) can set a password using this button too.
This also handles the wording change of the placeholder when posting a request.
Will somewhat close #375.
Closes #381

Improved wording for PW reset and fixed layout

---

.env
.env.development
public/locales/de/translation.json
src/appConfig.jsx
src/views/AskForHelp.jsx

* adds a feature to limit the number of open requests a user can have to avoid potential spam.
* in this case, we show a short hint explaining to the user that they should close one of their open entries first.
* hotline account can always create new posts

feat: add max amount of open requests per user

---

src/components/LocationInput.jsx

Richt now, if we have too many autocomplete suggestions, the box will overflow and later entries are not visible anymore. This PR limits the size of the autocomplete box and allows it to be scrollable to see all overflowing content.
Then:
https://user-images.githubusercontent.com/20804369/112139262-db165900-8bd2-11eb-9b2a-b06e091a18b3.mov
Now:
https://user-images.githubusercontent.com/20804369/112139410-0436e980-8bd3-11eb-8010-237fe5391673.mov

Made dropdown autocomplete scrollable

---

firebase/functions/src/utilities/email/sendEmailForAskForHelpEntries.ts
public/locales/de/translation.json
src/assets/loading.svg
src/components/Popup.jsx
src/components/entry/Entry.jsx

This PR adds a loading indicator when a user hits the button to request more help for the time the request is in progress. With this, the user is unable to spam the button if the request takes longer, e.g, on a cold start of the function.
https://user-images.githubusercontent.com/20641332/112736325-2ec9cf00-8f52-11eb-8ba8-e9cd45f662ce.mov
https://user-images.githubusercontent.com/20641332/112736322-2bcede80-8f52-11eb-8dd2-043e2e185a87.mov

feat: add loading indicator when request for more help is in progress

---

src/components/EntryList.jsx
src/components/LocationInput.jsx
src/components/NotifyMe.jsx
src/views/NotifyMe.jsx

* This PR adds functionality to carry over the selected postal code from the landing page to the notify me component, removing the necessity for the user to enter the location postal code again :)
https://user-images.githubusercontent.com/20641332/112738074-f03b1100-8f5f-11eb-9d47-c4786703f656.mov

Fix/carry over selected location from landing page to notify-me component

---

.github/workflows/deploy-firebase.yaml
.github/workflows/deploy-frontend.yaml
.github/workflows/pr.yml
firebase/functions/src/config.ts
firebase/functions/src/index.ts
public/index.html
src/views/Main.jsx

* removes email-related cloud functions
* lowers number of emails being sent
* removes mentions of hotline

Trim session 2023
