- src/components/FAQ.js
> Fix tiny typo in FAQ.

- package.json
- src/App.js
- src/components/DesktopMenu.js
- src/components/ShareButtons.js
- src/components/Sidebar/Sidebar.js
rebased version of https://github.com/kenodressel/quarantine-hero/pull/7 with yarn.lock issue resolved
> Yorickreum sharebuttons

- src/components/FilteredList.js
- src/components/NotifyMe.js
Changed wording to signalize that people will be notified if someone nearby the specified location needs help
Closes #19
> Pull request regarding issue #19

- src/components/Entry.js
- src/components/Impressum.js
Referring to #30 and #31 
Changed "Nachrichten erhalten" to "Antworten erhalten".
Replaced private address with address suggested in #31 .
> Wording improvements & Impressum update

- src/components/Dashboard.js
Fixed a typo and added links to respective sites.
> Fixed typo and added Links

- src/views/Presse.js
> Added "und viele mehr" footer

- src/components/Entry.jsx
- src/components/FilteredList.jsx
- src/views/AskForHelp.jsx
- src/views/Dashboard.jsx
- src/views/Impressum.jsx
- src/views/Signup.jsx
- src/views/VerifyEmail.jsx
Also added missing required tags and fixed a link style
> Fixed broken spacing

- src/views/Main.jsx
> fixed Aushang div size

- src/views/Dashboard.jsx
Fixes https://github.com/kenodressel/quarantine-hero/issues/41.
> Fix analytics event of 'subscribe region' link on dashboard page

- src/components/Sidebar.jsx
> Sidebar fixed

- src/views/AskForHelp.jsx
Before this change, it could happen that during local development, one suddenly and unexpectedly is taken to the production app.
> Use react-router Link to refer to /notify-me from /ask-for-help

- .env
- .env.development
- src/appConfig.jsx
- src/views/NotifyMe.jsx
- src/views/Signup.jsx
This makes it possible to test authentication locally when developping on
localhost:3000 by replacing `src/appConfig.jsx` with
`src/appConfig.dev.jsx`.
> Make base URL configurable for local dev

- package.json
- src/components/Entry.jsx
- src/views/AskForHelp.jsx
- src/views/Dashboard.jsx
- yarn.lock
to clean up our code. Fixes #64.
Adds dependency to [react-firebase-hooks](https://github.com/CSFrequency/react-firebase-hooks). Make use of the `useAuthState` hook in all components instead of simply accessing `fb.auth.currentUser` or own solution based on `useState` and `useEffect` (dashboard page).
**Checklist**
> Use hook for managing user state

- public/locales/de/translation.json
- src/views/AskForHelp.jsx
- src/views/CompleteOfferHelp.jsx
- src/views/Dashboard.jsx
- src/views/Main.jsx
- src/views/NotifyMe.jsx
- src/views/OfferHelp.jsx
- src/views/Overview.jsx
- src/views/Success.jsx
- src/views/SuccessOffer.jsx
As part of https://github.com/kenodressel/quarantine-hero/issues/24 this PR internationalizes the views  "AskForHelp", "CompleteOfferHelp", "Dashboard", "Main", "NotifyMe", "OfferHelp", "Overview", "Success" and "SuccessOffer".
**Checklist**
- @kenodressel
> Internationalisation of a bunch of views

- README.md
**Updated README**
Added a small section about contributions.
> README Update for better onboarding of open source contributions

- src/i18n.js
Hotfix to overwrite language detection by browser
> Hotfix: Forcing de as locale

- public/locales/de/translation.json
- src/App.jsx
- src/components/DesktopMenu.jsx
- src/components/ShareButtons.jsx
- yarn.lock
**This PR handles issue 122: Redesign desktop navigation**
- Two new entries were introduced to the translation.json file for the German language. The myOverview and safety keys.
- Changes were made on DesktopMenu and ShareButtons components as well as at the App component
If you have any questions be sure to let me know! For review ping anyone in this list:
- @kenodressel
- @Maurice22
- @tgraupne
> Redesign desktop navigation #122

- src/components/Entry.jsx
- src/styles/App.css
- src/styles/index.css
> Fix report flag positioning and entry top layout

- src/views/AskForHelp.jsx
- src/views/NotifyMe.jsx
- src/views/OfferHelp.jsx
- src/views/Signup.jsx
Prevent default form submit behaviour consistently
**Checklist**
> Prevent page reload on form submit

- src/views/Security.jsx
* fixes wording in Security text (`zwei Metern` instead of `2 m`)
* add `target_blank` to hrefs
> update security component content

- public/locales/de/translation.json
- src/views/Dashboard.jsx
* use useCollectionDataOnce hook from react-firebase-hooks library for
easier loading of data
* separate authentication into a separate component
* use placeholder when authentication information or data is loading
* pull definition of Notification function component out of Dashboard
function component. Nesting function components in this way is bad
because it prevents React from reusing parts of the virtual DOM,
since every time the outer component is executed, the inner component
is redefined.
**Checklist**
> Refactor Dashboard component

- src/components/Responses.jsx
Fixes #175.
Video: https://drive.google.com/file/d/1EBT3tfd3s3VVnattb04RzKmULN6qqR4u/view
**Checklist**
- @Maurice22
> Fix layout of responses on narrow screens (e.g. mobile)

- README.md
- firebase/README.md
- firebase/firebase.json
- firebase/functions/.eslintrc.json
- firebase/functions/.gitignore
- firebase/functions/index.js
- firebase/functions/package-lock.json
- firebase/functions/package.json
- firebase/functions/slack.js
- firebase/functions/utils.js
This merges the repo https://github.com/florianschmidt1994/quarantaenehelden-firebase-functions to this one. Main reasons being:
- allowing and encouraging holistic pull requests
- making it easier to find for contributors
- making it easier to host your own version and understanding the dependencies
**Checklist**
> adds firebase functions

- firebase/functions/index.js
- moves scheduled function to eu servers
- runs sendEmails every 3 minutes between 9:00 and 24:00 Berlin Time
**Additonal Info**
- git diff seems weird, only changed line 98 to 98 - 100
> Refactor firebase functions

- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
- SECURITY.md
- Add a CONTRIBUTING.md
- Add a SECURITY.md
- Add a MAINTAINERS.md
- Update README to link to CONTRIBUTING.md 
**Checklist**
> Improve contribution guidelines

- src/components/Entry.jsx
- src/components/FilteredList.jsx
- src/components/entry/Entry.css
- src/components/entry/Entry.jsx
- src/views/Dashboard.jsx
- src/views/OfferHelp.jsx
Break words properly to avoid overflow
_Before_
_After_
I've verified this on mobile and desktop
Close #159
> Break words in entry if too long

- MAINTAINERS.md
> add quarantaenehelden mails

- src/styles/index.css
Increased z-index of scroll up button to be on top of "melden" flag
> Increased z-index to be above "melden" flags

- src/views/Main.jsx
Fixed padding on mobile and made buttons grow on mobile too.
> Fixed button layout on mobile and made button always grow

- firebase/functions/index.js
> Enabled feature flag for searching by distance instead of PLZ

- src/views/Signup.jsx
- src/views/VerifyEmail.jsx
* adds redirect URL for email verification, which allows the user to navigate back to the website
* does **not** automatically redirect the user to the website (this is not possible with the selected auth method, as far as my research suggested)
> add redirect url for sendEmailVerification

- src/views/Signup.jsx
> Fixed the case in which returnUrl is undefiened

- cypress/util/createAskForHelpPosting.js
- public/locales/de/translation.json
- src/App.jsx
- src/components/StatusIndicator.jsx
- src/components/loader/Loader.jsx
- src/util/buildHash.js
- src/views/CompleteOfferHelp.jsx
- src/views/HandleEmailAction.jsx
- src/views/NotifyMe.jsx
- src/views/Signup.jsx
- src/views/Success.jsx
* Adds a new view which handles email action URLs generated by firebase
* Depending on the opcode, either email verification, password reset or email recovery is handled
* Closes #241 
**IMPORTANT: Once we merge this, we have to update the firebase settings under Authentication -> Email Templates and set the actionURL to 'https://quarantaenehelden.org/#/handle-email-action'** 
For testing the password recovery functionality, you have to change your account password. You can do so by adding the following code to a dummy component and clicking the button:
```
<button
type="button"
onClick={() => {
user.updateEmail('test@example.com');
}}
>
TestEmail change
</button>
```
> Own account management

- .github/workflows/deploy.yaml
I kinda broke the deployment 🙈
That should fix it.
> Fixing deployment action

- .github/workflows/deploy.yaml
Fixed file reference in deployment action
> Fixed file reference

- .github/workflows/deploy.yaml
- src/App.jsx
Add Git SHA to build process and use it to tag sentry releases.
Related to #289
> Tag releases with SHA for sentry

- src/components/OnePagers.jsx
Let drawer for one pagers open and close dynamically with an animation.
> Let drawer for one pagers open and close dynamically with an animation.

- src/views/HandleEmailAction.jsx
> Fixed unnecessary error reporting when opening email action handler

- firebase/functions/index.js
- firebase/functions/package-lock.json
- firebase/functions/package.json
- package.json
- yarn.lock
* Currently, all our emails are sent to the wrong recipients. The audience of an email for an ask-for-help entry is determined randomly, as our querying functionality is broken.
* upgrades `geofirestore` to `3.6.0`, as the current version was silently accepting undefined `coordinates` input. As a result, `notificationsRef.near({ center: coordinates, radius: 30 });` would yield all of the entries in the database. Finally, this would lead to us sending email to random people, who are not in the vicinity of the person in need 🐛 
* Fix was tested on DEV, works
> fixes issues with emails being sent to random people

- src/views/NotifyMe.jsx
- src/views/OfferHelp.jsx
* prefills the user email on `notify-me` and `offer-help` if the user is logged in.
* fixes #326
> prefill user email on notify-me and offer-help

- public/locales/de/translation.json
> FAQ update

- src/views/FAQ.jsx
> Made FAQs collapsable and refactored component

- firebase/README.md
- firebase/functions/package.json
Firebase will deprecate the NodeJS 8 runtime, hence we updated the runtime to NodeJS 10
Closes #327
> Update Firebase Function NodeJS runtime

- firebase/functions/package-lock.json
> Removed stocard references

- .github/workflows/deploy-firebase.sh
- firebase/firebase.json
- firebase/firestore.indexes.json
- firebase/firestore.rules
> adds firebase rules to repo and deploy script (fixes #287)

- firebase/functions/src/index.ts
Currently, we only take a backup of the CMS content whenever fields are updated, but that does not include write or delete actions. This PR changes the trigger from `onUpdate` to `onWrite` to trigger on all these events.
> Extended trigger to also handle crate and delete events

- src/views/Imprint.jsx
Updated imprint information and added information about registration
Closes #357
> Imprint update

- public/index.html
Idea: update the description in the head tag to score better results when searching for the usual keywords:
* `corona + hilfe`
* `corona + nachbarschaftshilfe`
* `corona + quarantäne`
* `corona + einkaufen`
* `corona + gassi gehen`
* etc..
Inspired by:
Part of https://github.com/option26/quarantine-hero/issues/325
Text to be discussed of course 😄 Just want to make sure we hit them keywords. Also, no SEO expert, so if there are possible downsides to this, please raise them :)
> SEO: first updated description suggestion

- firebase/functions/src/domain/onAskForHelpCreate.ts
- firebase/functions/src/domain/onReportedPostsCreate.ts
- firebase/functions/src/domain/searchAndSendNotificationEmails.ts
- firebase/functions/src/types/interface/collections/AskForHelpCollectionEntry.ts
- firebase/functions/src/utilities/slack.ts
Using postMessage API instead of webhook now. The Slack Bot now also informs about how many emails were sent and when a post gets reported.
> Enhanced Slack integration

- firebase/functions/src/domain/onReportedPostsCreate.ts
- firebase/functions/src/domain/searchAndSendNotificationEmails.ts
Fixed relative paths to import
> Fixed relative paths to import

- firebase/functions/src/domain/searchAndSendNotificationEmails.ts
Now also posts to slack if emails are activated :)
> Fixed an error where posting to slack was only done if emails were deactivated

- src/components/EntryMap.jsx
Limits the ask-for-help entries that are queried in the map view on three month
> Limits the ask-for-help entries in map view

- firebase/functions/src/domain/onDeletePost.ts
- firebase/functions/src/utilities/slack.ts
- firebase/functions/tsconfig.json
Adds an interactive slack action that can delete posts.
> Added integration to delete a post from slack

- public/locales/de/translation.json
adjusts number to display local number instead of the twilio managed one.
> chore(translation): adjust phone number away from twilio

- src/views/AskForHelp.jsx
Fixes an issue where there was an invalid constant in a dependency array
> Fixed an issue within a dependency array

- firebase/functions/src/utilities/utils.ts
Fixes a bug where the promise of the recursive deletion was never resolved, leading to a timeout in the calling functions.
FYI, this is already on prod because I did an oopsie
> fix: recursive deletion

- firebase/functions/src/domain/handleAskForMoreHelp.ts
- firebase/functions/src/domain/onIncreaseReach.ts
- firebase/functions/src/domain/sendEmailsForOpenOffersWithAnswers.ts
- firebase/functions/src/domain/sendEmailsForOpenOffersWithoutAnswers.ts
- firebase/functions/src/domain/sendNotificationsForHotlineRequests.ts
- firebase/functions/src/index.ts
- firebase/functions/src/utilities/slack.ts
* adds functionality to increase reach for hotline posts via slack
* co-authored by @mauriceackel
> feat: increase reach slack integration

- .editorconfig
- adds .ts file rules to editor config
> chore(config): adds ts to editorconfig

- src/views/Main.jsx
* adds a section on the landing page about the possibility to add posts for initiatives around Ukraine
> feat: add standwithukraine section

- .github/workflows/deploy-firebase.sh
- fixes firebase cli version to 8
> chore: sets fixed firebase version

- .github/workflows/deploy-firebase.yaml
- .github/workflows/deploy-frontend.yaml
- adds workflow dispatch trigger
- adds frontend action for github actions deploy
> fix: deploy pipeline

- .github/workflows/deploy-firebase.sh
- .github/workflows/deploy-firebase.yaml
> Fixed firebase deployment
